import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import RatingMain from '@/components/RatingMain';
import AddPlayerForm from '@/components/AddPlayerForm';
import AddGameForm from '@/components/AddGameForm';
import { openPopup, closePopup } from '@/utils/functions';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [isAddPlayerPopupOpen, setIsAddPlayerPopupOpen] = useState(false);
  

  // function openPopup(setState: (value: boolean) => void) {
  //   setState(true);
  // }
  // function closePopup() {
  //   setIsAddPlayerPopupOpen(false);
    
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <RatingMain handleAddPlayer={() => openPopup(setIsAddPlayerPopupOpen)} />
      <AddPlayerForm isOpen={isAddPlayerPopupOpen} onClose={()=> closePopup(setIsAddPlayerPopupOpen)} />
      
    </>
  );
}
